version: 0.2

phases:

  pre_build:
    commands:
      # DI CHUYỂN VÀO THƯ MỤC CHỨA SOURCE CODE CỦA PFM
      - cd service/pfm  
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      
  build:
    commands:
      # Bắt buộc phải cd lại (hoặc đảm bảo đang ở đúng thư mục) để nhận diện file Dockerfile và pom.xml khi build
      - cd $CODEBUILD_SRC_DIR/service/pfm
      - echo Build started on `date`
      - echo Building the Docker image...          
      # Lệnh build sẽ lấy Dockerfile tại thư mục hiện tại (.)
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

