FROM maven:3.9.6-eclipse-temurin-17-alpine AS build
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B


COPY src ./src


RUN mvn package -DskipTests


FROM eclipse-temurin:17-jre-alpine
WORKDIR /app



COPY --from=build /app/target/pfm-1.0-SNAPSHOT.jar app.jar


EXPOSE 8080


ENTRYPOINT ["java", "-jar", "app.jar"]